<?php include __DIR__ . '/../layouts/header_login.php'; ?>

<div class="container mt-5" style="max-width: 500px;">
    <h2 class="mb-4"><i class="fas fa-shield-alt"></i> Two-Factor Authentication</h2>

    <?php if (!empty($_SESSION['2fa_error'])): ?>
        <div class="alert alert-danger">
            <?= htmlspecialchars($_SESSION['2fa_error']) ?>
        </div>
        <?php unset($_SESSION['2fa_error']); ?>
    <?php endif; ?>

    <p>Scan the QR code below using Google Authenticator app (or any TOTP app):</p>

    <div class="text-center mb-4">
        <img src="<?= htmlspecialchars($qrCodeUrl) ?>" alt="Scan this QR code with Google Authenticator">

    </div>

    <p>Then enter the 6-digit code generated by your app:</p>

    <form method="POST" action="<?= url('2fa/verify') ?>">
        <div class="mb-3">
            <label for="code" class="form-label">Authentication Code</label>
            <input type="text" class="form-control" id="code" name="code" pattern="\d{6}" maxlength="6" required
                autofocus autocomplete="one-time-code" inputmode="numeric" placeholder="Enter 6-digit code">
        </div>
        <button type="submit" class="btn btn-primary w-100">
            Verify
        </button>
    </form>
</div>

<?php include __DIR__ . '/../layouts/footer.php'; ?>